platform :ios, '10.0'

target 'HorizontalFloatingHeaderLayout_Example' do
	use_frameworks!
  	pod "HorizontalFloatingHeaderLayout", :path => "../"
  	target 'HorizontalFloatingHeaderLayout_Tests' do
	end
end
